name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: gcc src/*.c src/cutils/*.c -Iinclude -Iinclude/cutils -s -Og -ggdb -o easymake-gdb-x86_64
    - name: make check
      run: ./easymake-gdb-x86_64 actions-test
    - uses: actions/upload-artifact@v2
      with:
        name: easymake-gdb-x86_64
        path: easymake-gdb-x86_64
