name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: gcc src/*.c -Iinclude -s -Og -ggdb -o easymake
    - uses: actions/upload-artifact@v2
      with:
        name: easymake
        path: easymake
